services:
    main:
        image: mcr.microsoft.com/vscode/devcontainers/base:bullseye
        init: true
        tty: true
        cap_add:
            - IPC_LOCK
        volumes:
            - ..:/workspace:cached
        networks:
            - main

    rdb:
        image: mysql:8.2.0
        container_name: rdb
        environment:
            TZ: "+00:00"
            MYSQL_USER: "remote_user"
            MYSQL_PASSWORD: "remote_password"
            MYSQL_ROOT_PASSWORD: "root_password"
        command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_bin"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "remote_user", "-premote_password"]
            interval: 10s
            timeout: 5s
            retries: 15

        ports:
            - 3306:3306
        expose:
            - 3306
        cap_add:
            - SYS_NICE
        volumes:
            - ./rdb:/docker-entrypoint-initdb.d
            - ./rdb/mysql/conf.d:/etc/mysql/conf.d
        networks:
            - main

    backend_python:
        container_name: python_service
        build:
            context: ../backend/python_service # Dockerfile があるディレクトリを指定
        tty: true
        ports:
            - "5010:5010"
        volumes:
            - ../backend/python_service:/apps
        networks:
            - main
    backend_nodejs:
        container_name: node_service
        build:
            context: ../backend/node_service # Dockerfile があるディレクトリを指定
        tty: true
        ports:
            - "6010:6010"
        volumes:
            - ../backend/node_service:/usr/src/app
        networks:
            - main

networks:
    main:
        driver: bridge
        enable_ipv6: false
