name: ESLint

on: [pull_request]

jobs:
    eslint:
        name: eslint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3 # ✅ `v1` → `v3` に更新
            - name: Install Node.js
              uses: actions/setup-node@v3 # ✅ Node.js のセットアップ
              with:
                  node-version: 18 # 必要なら Node.js バージョンを指定
            - name: Install dependencies
              run: npm install --prefix web/apps
            - name: Run ESLint with Reviewdog
              uses: reviewdog/action-eslint@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }} # ✅ 小文字から大文字へ修正
                  reporter: github-pr-review
                  eslint_flags: "--ext .vue,.ts,.js,.tsx ." # ✅ 修正されたフラグ
                  fail_level: error
            - name: Run ESLint manually
              run: npm run lint
              working-directory: web/apps
